#
# See .github/workflows/README.md.
#

name: Autoload Test

on:
  workflow_dispatch:

env:
  OLDEST_DEPS: 'ipython==7.23.1'
  LATEST_DEPS: 'ipython'

jobs:
  full:
    name: Full
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.15']
        dependencies: [ 'oldest', 'latest' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout LiveImport
      uses: actions/checkout@v5

    - name: Prepare Pip Cache Key
      shell: bash
      run: |
        date -u +'%G-%V' > .pip-cache-key
        echo "${{ matrix.dependencies }}" >> .pip-cache-key

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: 'pip'
        cache-dependency-path: |
          .pip-cache-key

    - name: Run Autoload Tests
      shell: bash
      env:
        AUTOLOAD_DEPENDENCIES: ${{ matrix.dependencies }}
      run: bash .github/scripts/test-autoload.sh
