name: Integration Test

on:
  pull_request:
  workflow_dispatch:

env:
  OLDEST_DEPS: 'ipython==7.23.1 notebook==5.7.0 coverage'
  LATEST_DEPS: 'ipython notebook coverage'

#
# Before running the complete matrix of tests, we test the "canary"
# configuration: Python 3.12 on Linux using both the oldest and latest versions
# of IPython and notebook.  Because of the nature LiveImport, if the canary
# tests fail, likely many if not all of the remaining tests will fail.
#
# "Latest" here with respect to IPython and notebook means unpinned.  The
# specific package version depends on the Python version running the tests.
#
# We rotate the setup-python pip cache key weekly and also use separate keys
# for oldest vs latest dependencies.  Rotation makes sense because caches are
# write once -- newer versions of packages will not be cached until the key
# changes.
#

jobs:
  canary:
    name: Canary [ubuntu-latest, 3.12]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependencies: [ 'oldest', 'latest' ]
      fail-fast: false
    steps:
    - name: Checkout LiveImport
      uses: actions/checkout@v5

    - name: Prepare Pip Cache Key
      shell: bash
      run: |
        # Make cache specific to oldest/latest and refresh it weekly.
        date -u +'%G-%V' > .pip-cache-key
        echo "${{ matrix.dependencies }}" >> .pip-cache-key

    - name: Setup Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: |
          .pip-cache-key

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        if [ "${{ matrix.dependencies }}" = "oldest" ]; then
          python -m pip install $OLDEST_DEPS
        else
          python -m pip install $LATEST_DEPS
        fi
        python -m pip install -e .

    - name: Run Tests
      run: |
        coverage run --branch \
            --data-file .coverage.main \
            --include 'src/liveimport/*.py' test/main.py -failstop
        coverage combine
        coverage report --include=src/liveimport/*.py --fail-under=100

    - name: Check Autoload
      uses: $/.github/actions/check-autoload
      with:
        repository: PyPI

  full:
    name: Full
    needs: canary
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.15']
        dependencies: [ 'oldest', 'latest' ]
        exclude:
          - os: ubuntu-latest
            python-version: '3.12'
            dependencies: 'oldest'
          - os: ubuntu-latest
            python-version: '3.12'
            dependencies: 'latest'
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout LiveImport
      uses: actions/checkout@v5

    - name: Prepare Pip Cache Key
      shell: bash
      run: |
        # Refresh unpinned dependencies weekly while reusing previous downloads.
        date -u +'%G-%V' > .pip-cache-key
        echo "${{ matrix.dependencies }}" >> .pip-cache-key

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: 'pip'
        cache-dependency-path: |
          .pip-cache-key

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        if [ "${{ matrix.dependencies }}" = "oldest" ]; then
          python -m pip install $OLDEST_DEPS
        else
          python -m pip install $LATEST_DEPS
        fi
        python -m pip install -e .
      shell: bash

    - name: Run Tests
      run: |
        coverage run --branch \
            --data-file .coverage.main \
            --include 'src/liveimport/*.py' test/main.py -failstop
        coverage combine
        coverage report --include=src/liveimport/*.py --fail-under=100
      shell: bash

    - name: Check Autoload
      uses: $/.github/actions/check-autoload
      with:
        repository: PyPI